name: template
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  # cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
