name: services
description: A lightweight version of a DartPad backend.
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  analysis_server_lib: any
  args: ^2.3.0
  json_annotation: ^4.8.1
  path: any
  shelf_router: ^1.1.0
  shelf: ^1.4.0

dev_dependencies:
  build_runner: any
  http: ^1.0.0
  json_serializable: any
  lints: ^2.0.0
  test: ^1.21.0
